[build]
  publish = "build"
  command = "npm run build && cd netlify/functions && npm install"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.development]
  environment = { NODE_ENV = "development" }
